### ISSUE TITLE
check basic validity of desktop and appstream before publishing

### ISSUE THREAD

**Issue by ramcq** [flathub-infra/buildbot-config#9]
Discord doesn't appear in GNOME Software, so must be missing some key fields. We should validate the basic stuff is there (meeting our submission guidelines) before publishing.

**Comment by TingPing** [comment]
> Discord doesn't appear in GNOME Software, so must be missing some key fields. 

This is because any package using `extra-data` will not have an icon downloaded and `gnome-software` does not show these.

This has been discussed with @hughsie and the solution is we need to find/host their icons somewhere and `appstream-util validate-relax` needs to be relaxed further to consider remote icons valid.

**Comment by bbhtt** [comment]
Linter does both and a lot more https://github.com/flathub-infra/flatpak-builder-lint
